export const COUNTRY_TO_ISO = {
  'Bahrain': 'bh',
  'Saudi Arabia': 'sa',
  'Australia': 'au',
  'Japan': 'jp',
  'China': 'cn',
  'United States': 'us',
  'Italy': 'it',
  'Monaco': 'mc',
  'Canada': 'ca',
  'Spain': 'es',
  'Austria': 'at',
  'United Kingdom': 'gb',
  'Hungary': 'hu',
  'Belgium': 'be',
  'Netherlands': 'nl',
  'Singapore': 'sg',
  'Mexico': 'mx',
  'Brazil': 'br',
  'UAE': 'ae',
  'Azerbaijan': 'az',
  'France': 'fr',
  'Portugal': 'pt',
  'Qatar': 'qa',
  'Las Vegas': 'us',
  'Miami': 'us',
}
